version: '3.3'

services:
  app:
    container_name: 'g-url'
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "1337:1337"
    stdin_open: true
    env_file:
      - .env
    command: yarn dev
volumes:
  node_modules: