version: '3.7'
services:
  gurl-app:
    build: .
    container_name: gurl-container
    networks:
      - gurl-networks
    ports:
      - 1337:1337
    volumes:
      - .:/app
networks:
  gurl-networks: